name: 🔗 Check for Broken Links

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 1'  # every Monday at 03:00 UTC

jobs:
  link-checker:
    runs-on: ubuntu-latest
    name: Run Lychee to detect broken links

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Lychee on the project
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: >
            --verbose
            --no-progress
            --exclude-mail
            --accept 200,429
            ./  # scans everything in repo
